### ISSUE TITLE
Cannot upload coverage report because request is throttled

### ISSUE THREAD

**Issue by NoNameProvided** [codecov/uploader#751]
**Describe the bug**

We just switched from the deprecated [codecov-node package](https://github.com/codecov/codecov-node) to this one but our coverage upload fails 100% times with the following error message: 
```
[2022-05-05T09:36:15.387Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 429 - Too Many Requests - {'detail': ErrorDetail(string='Request was throttled.', code='throttled')}
```

The used config for the action:
```
- name: Upload coverage report for test:unit
   uses: codecov/codecov-action@v2
   with:
     token: ${{ secrets.CODECOV_TOKEN }}
     directory: ./coverage/
```

**To Reproduce**
1. Add specified configuration
2. Push any commit
3. Check the result of the Github Action run
4. See the error

**Expected behavior**
The upload works without issues.

**Screenshots**
n/a
**Additional context**
n/a
